name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Install Rye
      run: |
        env curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
    - name: Rye Sync
      run: |
        source ~/.rye/env
        rye sync
    - name: Tox
      run: |
        source ~/.rye/env
        rye run tox
